# .github/workflows/python-lambda-tests.yml
name: Python Lambda Tests

on:
  workflow_call:
    inputs:
      lambda-path:
        required: true
        type: string
      test-type:
        required: true
        type: string
      python-version:
        type: string
        default: "3.11"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: pip
          cache-dependency-path: |
            ${{ inputs.lambda-path }}/requirements.txt

      - name: Install deps
        run: |
          pip install -r ${{ inputs.lambda-path }}/requirements.txt

      - name: Run tests
        run: |
          if [ "${{ inputs.test-type }}" = "unit" ]; then
            pytest ${{ inputs.lambda-path }}/tests/unit
          else
            pytest ${{ inputs.lambda-path }}/tests/integration
          fi
